language: node_js
node_js:
- '4'
- stable

notifications:
  email: false
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/54f8a1e753f859f5ca1a
    on_start: never
    on_failure: change

deploy:
  provider: npm
  email: hello@trailsjs.io
  api_key:
    secure: rsu0xEkxmIyXfwuwJ8bzMOHwASLbxUyOSTKFv85Ta1+pVWednvJeK4CJQJ03iZjP1iY4REb9IKJX/SeCnU6JJ9iMOvCXG8sjXdih4qLLLSuBwsRwyAFPNCephIOsNhHR0n1fHrtxMdAZo9/aMnsvp24Jqwjd+5w7DRu+ja1IRN6N+20I7jl+bdSyS7eXmqkMNanwZMN7bKUyro91Kz6/RHLyuK7FkIhIBhmQUsqNyxkMhshc2RBVS9dqLCUyZ+tySPKojRlBl2Te/5Q/0s36ziz6gaM+7YaDP60w9fVBhc176b6+C9EmHuI5hSGbY5pzzL5iqwkWaAc8oYVQ2lm1xi4FRlFMVGoXz40TABoRUgsoas+YbKtaLXZ9CSY5BRyAC12xNIvJtCgxarkHndHOBwIqmEb+QVVjlDY4gN9vOWb+hqYx01M7qB0DWeccTzZ06yshYDwesphO91rC3Gbn4bi8CQ6V2iXU0fSuHCu/68JsTgpARCI8pR8B++WMbjnhdy4/4wQmHXdhaT5dG7dXOt0oOvNad8Fonk7NfanE9KB80q5QJjfs95GijpzKRfH21Wc9V9GPFjUte9BLCvi+oke+eElXJcw6ad3DCAMiz38JXsjDNnj9knQ2s1leskyvRaSc6qGUBsL3SdG0cclfLelk1rsepjwc+/QtcEEYaII=
  on:
    tags: true
    repo: trailsjs/trailpack
    node: stable
